name: Build and Publish Docker Image
# jobs:
#   job1:
#   job2:
#     needs: job1
#   job3:
#     needs: [job1, job2]
on: [push]

jobs:
  build-and-publish:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    ## checks out our project source code
    - uses: actions/checkout@v2
    
    ## Builds our docker image!
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

    ## Publishes our image to Docker Hub 😎
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        ## the name of our image
        name: vickydeploys/go-appv1
        ## Here we pass in our Docker Username
        username: ${{ secrets.DOCKER_USERNAME }}
        ## and our Docker password which 
        password: ${{ secrets.DOCKER_PASSWORD }}